### ISSUE TITLE
Dependencies mistype

### ISSUE THREAD

**Issue by bendikl** [tooling/book-of-modern-frontend-tooling#91]
Dependencies is mistyped under https://github.com/tooling/book-of-modern-frontend-tooling#depedencies

Small thing, but perfectionists feel their eyes bleeding. ;-)

**Comment by iampeterbanjo** [comment]
Can this issue now be closed or is there a review/other process?

**Comment by bendikl** [comment]
Looks good to me :)

![image](https://cloud.githubusercontent.com/assets/9542610/10017301/7db42d44-612d-11e5-95b3-dea6383cb15b.png)

**Comment by iampeterbanjo** [comment]
Lol! :-D
